#!/bin/bash

### quantify in parallel

#PBS -N batch_run_quantification
#PBS -l select=1:ncpus=1:mem=64gb
#PBS -l walltime=6:00:00
#PBS -o /home/z3536241/src/blana/Alex/PBS/log
#PBS -e /home/z3536241/src/blana/Alex/PBS/log

### The following parameter is modulated at runtime to specify the
### batch number on each node. Batches should run from zero to N_BATCHES-1
### to process all files

#PBS -J 0-35

###---------------------------------------------------------------------------

source /home/z3536241/.bashrc
conda activate berrylab-py310

cd $PBS_O_WORKDIR

python /home/z3536241/src/blana/Alex/250902_mACmChPOLR2A_AuxinWashout/run_quantification_488.py \
  --id ${PBS_ARRAY_INDEX} \
  --illumination_correction_file /srv/scratch/berrylab/z3536241/NikonSpinningDisk/250822_mACmChPOLR2A_AuxinWashout/20250825_193134_323/QUICK_ILLCORR/QUICK_ILLCORR_20X_488.pkl \
  --features_dir /srv/scratch/berrylab/z3536241/NikonSpinningDisk/250902_mACmChPOLR2A_AuxinWashout/20250905_184506_514/QUANTIFICATION-488 \
  --input_dir /srv/scratch/berrylab/z3536241/NikonSpinningDisk/250902_mACmChPOLR2A_AuxinWashout/20250905_184506_514/OME-TIFF-MIP-488 \
  --label_dir /srv/scratch/berrylab/z3536241/NikonSpinningDisk/250902_mACmChPOLR2A_AuxinWashout/20250905_184506_514/SEGMENTATION

conda deactivate
