#!/bin/bash

### quantify in parallel

#PBS -N batch_run_quantification
#PBS -l select=1:ncpus=1:mem=16gb
#PBS -l walltime=1:00:00
#PBS -o /srv/scratch/berrylab/z3532965/operetta_cls/ARMC5_TransInhib/PBS/log/
#PBS -e /srv/scratch/berrylab/z3532965/operetta_cls/ARMC5_TransInhib/PBS/log/
#PBS -M scott.berry@unsw.edu.au
#PBS -m ae

### The following parameter is modulated at runtime to specify the
### batch number on each node. Batches should run from zero to N_BATCHES-1
### to process all files

#PBS -J 0-2378

###---------------------------------------------------------------------------

source /home/z3532965/.bashrc
conda activate berrylab-py310

cd $PBS_O_WORKDIR

dataset="231110_ARMC5_TransInhib/231110_ARMC5_TransInhib__2023-11-14T18_12_24-Measurement 1"

python /srv/scratch/z3532965/src/publications/2024_ARMC5/hct116_inhibitors_IF/run_quantification_IF.py \
  --id ${PBS_ARRAY_INDEX} \
  --illumination_correction_file "/srv/scratch/berrylab/z3532965/operetta_cls/ARMC5_TransInhib/${dataset}/ILLUMCORR/illumination_correction.pkl" \
  --cellpose_model_file /srv/scratch/berrylab/z3532965/model_weights/40X_DAPI_operetta_20240705_162749 \
  --features_dir "/srv/scratch/berrylab/z3532965/operetta_cls/ARMC5_TransInhib/${dataset}/QUANTIFICATION" \
  --input_dir "/srv/scratch/berrylab/z3532965/operetta_cls/ARMC5_TransInhib/${dataset}/OME-TIFF-MIP" \
  --output_dir "/srv/scratch/berrylab/z3532965/operetta_cls/ARMC5_TransInhib/${dataset}/SEGMENTATION"

conda deactivate
