
#!/bin/bash

### skimage filter in parallel

#PBS -N batch_run_filter
#PBS -l select=1:ncpus=1:mem=64gb
#PBS -l walltime=8:00:00
#PBS -o /home/z3536241/src/blana/Alex/PBS/log/
#PBS -e /home/z3536241/src/blana/Alex/PBS/log/

### The following parameter is modulated at runtime to specify the
### batch number on each node. Batches should run from zero to N_BATCHES-1
### to process all files

#PBS -J 0-356

###---------------------------------------------------------------------------

source /home/z3536241/.bashrc
conda activate berrylab-py310

cd $PBS_O_WORKDIR

python /home/z3536241/src/blana/Alex/251031_mACmChPOLR2A_smFISH/run_segment.py \
 --id ${PBS_ARRAY_INDEX} \
 --input_dir /srv/scratch/berrylab/z3536241/NikonSpinningDisk/251031_mACmChPOLR2A_smFISH/20251104_181151_686/OME-TIFF \
 --illumination_correction_file /srv/scratch/berrylab/z3536241/NikonSpinningDisk/250922_mACmChPOLR2A_smFISH/ILLCORR/ILLCORR_100X_647_488_561_405.pkl \
 --output_dir /srv/scratch/berrylab/z3536241/NikonSpinningDisk/251031_mACmChPOLR2A_smFISH/20251104_181151_686/SEGMENTATION

conda deactivate
