#!/bin/bash

### Splits nd2 files into standard OME-TIFF format

#PBS -N ConvertND2
#PBS -l select=1:ncpus=1:mem=128gb
#PBS -l walltime=08:00:00
#PBS -o /srv/scratch/z3532965/src/blana/20260626_POLR2A_heterogeneity/log/
#PBS -e /srv/scratch/z3532965/src/blana/20260626_POLR2A_heterogeneity/log/
#PBS -M scott.berry@unsw.edu.au
#PBS -m ae

### The following parameter is modulated at runtime to specify the
### batch number on each node. Batches should run from zero to N_BATCHES-1
### to process all files

#PBS -J 0-11

###---------------------------------------------------------------------------

INPUT_DIR="/srv/scratch/berrylab/z3532965/systems_Ti2/20260626_POLR2A_heterogeneity/20260629_134305_894"
OUTPUT_DIR="/srv/scratch/berrylab/z3532965/systems_Ti2/20260626_POLR2A_heterogeneity/20260629_134305_894/OME-TIFF"

source /home/z3532965/.bashrc
conda activate berrylab-py310

cd $PBS_O_WORKDIR

python /srv/scratch/z3532965/src/blimp/blimp/preprocessing/nd2_to_ome_tiff.py \
-i "$INPUT_DIR" -o "$OUTPUT_DIR" --batch 12 ${PBS_ARRAY_INDEX} \
--mip  -y down 

conda deactivate
