#!/bin/bash

### quantify in parallel

#PBS -N batch_run_quantification
#PBS -l select=1:ncpus=1:mem=16gb
#PBS -l walltime=1:00:00
#PBS -o /home/z3536241/src/blana/Alex/PBS/log/
#PBS -e /home/z3536241/src/blana/Alex/PBS/log/

### The following parameter is modulated at runtime to specify the
### batch number on each node. Batches should run from zero to N_BATCHES-1
### to process all files

#PBS -J 0-2160

###---------------------------------------------------------------------------

source /home/z3536241/.bashrc
conda activate berrylab-py310

cd $PBS_O_WORKDIR

python /home/z3536241/src/blana/Alex/241111_mACmChPOLR2A_ActivePolII/run_quantification_cycle2.py \
  --id ${PBS_ARRAY_INDEX} \
  --illumination_correction_file /srv/scratch/berrylab/z3536241/NikonSpinningDisk/SpinningDisk_IlluminationCorrection/202409_NikonSpinningDisk_20X_647_405/ILLUM_CORR_20X_647_405.pkl \
  --features_dir /srv/scratch/berrylab/z3536241/NikonSpinningDisk/241111_mACmChPOLR2A_ActivePolII/20241115_164752_840/QUANTIFICATION \
  --input_dir /srv/scratch/berrylab/z3536241/NikonSpinningDisk/241111_mACmChPOLR2A_ActivePolII/20241115_164752_840/OME-TIFF-MIP \
  --output_dir /srv/scratch/berrylab/z3536241/NikonSpinningDisk/241111_mACmChPOLR2A_ActivePolII/20241115_164752_840/SEGMENTATION

conda deactivate
