#!/bin/bash

### quantify in parallel

#PBS -N batch_run_quantification
#PBS -l select=1:ncpus=1:mem=16gb
#PBS -l walltime=1:00:00
#PBS -o /home/z3536241/src/blana/Alex/PBS/log/
#PBS -e /home/z3536241/src/blana/Alex/PBS/log/

### The following parameter is modulated at runtime to specify the
### batch number on each node. Batches should run from zero to N_BATCHES-1
### to process all files

#PBS -J 0-960

###---------------------------------------------------------------------------

source /home/z3536241/.bashrc
conda activate berrylab-py310

cd $PBS_O_WORKDIR

python /home/z3536241/src/blana/Alex/250822_PTEFB_SIRNA/run_quantification.py \
  --id ${PBS_ARRAY_INDEX} \
  --illumination_correction_file /srv/scratch/berrylab/z3536241/NikonSpinningDisk/SpinningDisk_IlluminationCorrection/202505_20X_647_405_XXX_488/ILLCORR_20X_647_405_XXX_488.pkl \
  --features_dir /srv/scratch/berrylab/z3536241/NikonSpinningDisk/250822_PTEFB_SIRNA/20250826_170901_845/QUANTIFICATION \
  --input_dir /srv/scratch/berrylab/z3536241/NikonSpinningDisk/250822_PTEFB_SIRNA/20250826_170901_845/OME-TIFF-MIP \
  --output_dir /srv/scratch/berrylab/z3536241/NikonSpinningDisk/250822_PTEFB_SIRNA/20250826_170901_845/SEGMENTATION

conda deactivate
