#!/bin/bash

#PBS -N batch_segment
#PBS -l select=1:ncpus=1:mem=64gb
#PBS -l walltime=1:00:00
#PBS -o /srv/scratch/berrylab/z3532965/log
#PBS -e /srv/scratch/berrylab/z3532965/log
#PBS -M scott.berry@unsw.edu.au
#PBS -m ae

### The following parameter is modulated at runtime to specify the
### batch number on each node. Batches should run from zero to N_BATCHES-1
### to process all files

#PBS -J 0-959
###---------------------------------------------------------------------------

source /home/z3532965/.bashrc
conda activate cellpose4-env-minimal

cd $PBS_O_WORKDIR

python /srv/scratch/z3532965/src/publications/2026_POLR2A_homeostasis/Imaging/NikonSpinningDisk/mACPOLR2A_CRC_EU/260515_mACPOLR2A_CRC_EU/run_segment_cycle2.py \
 --input_dir /srv/scratch/berrylab/z3536241/NikonSpinningDisk/260515_mACPOLR2A_CRC_EU/20260519_171947_338/OME-TIFF-MIP \
 --illumination_correction_file /srv/scratch/berrylab/z3532965/NikonSpinningDisk/260515_mACPOLR2A_CRC_EU/20260519_171947_338/ILLCORR/ILLCORR_20x_647_405_561_XXX.pkl \
 --output_dir /srv/scratch/berrylab/z3532965/NikonSpinningDisk/260515_mACPOLR2A_CRC_EU/20260519_171947_338/SEGMENTATION \
 --id ${PBS_ARRAY_INDEX}

conda deactivate
