
#!/bin/bash

### skimage filter in parallel

#PBS -N batch_run_filter
#PBS -l select=1:ncpus=1:mem=64gb
#PBS -l walltime=8:00:00
#PBS -o /home/z3536241/src/blana/Alex/PBS/log/
#PBS -e /home/z3536241/src/blana/Alex/PBS/log/

### The following parameter is modulated at runtime to specify the
### batch number on each node. Batches should run from zero to N_BATCHES-1
### to process all files

#PBS -J 0-959
###---------------------------------------------------------------------------

source /home/z3536241/.bashrc
conda activate berrylab-py310

cd $PBS_O_WORKDIR

python /home/z3536241/src/blana/Alex/260518_mAC_mACmCh_TotalPolII/run_segment.py \
 --id ${PBS_ARRAY_INDEX} \
 --input_dir /srv/scratch/berrylab/z3536241/NikonSpinningDisk/260518_mAC_mACmCh_TotalPolII/20260524_154125_815/OME-TIFF-MIP \
 --illumination_correction_file /srv/scratch/berrylab/z3536241/NikonSpinningDisk/260518_mAC_mACmCh_TotalPolII/20260524_154125_815/ILLCORR/ILLCORR_20x_647_488_561_405.pkl \
 --output_dir /srv/scratch/berrylab/z3536241/NikonSpinningDisk/260518_mAC_mACmCh_TotalPolII/20260524_154125_815/SEGMENTATION

conda deactivate
