#!/bin/bash

### quantify in parallel

#PBS -N batch_run_quantification
#PBS -l select=1:ncpus=1:mem=16gb
#PBS -l walltime=1:00:00
#PBS -o /home/z3536241/src/blana/Alex/PBS/log/
#PBS -e /home/z3536241/src/blana/Alex/PBS/log/

### The following parameter is modulated at runtime to specify the
### batch number on each node. Batches should run from zero to N_BATCHES-1
### to process all files

#PBS -J 0-354

###---------------------------------------------------------------------------

source /home/z3536241/.bashrc
conda activate berrylab-py310

cd $PBS_O_WORKDIR

python /home/z3536241/src/blana/Alex/260127_ARMC5mAC_PhosphoEU/run_quantification_cycle2.py \
  --id ${PBS_ARRAY_INDEX} \
  --illumination_correction_file /srv/scratch/berrylab/z3536241/NikonSpinningDisk/260127_ARMC5mAC_PhosphoEU/20260203_171323_021/ILLCORR/ILLCORR_20x_647_405.pkl \
  --features_dir /srv/scratch/berrylab/z3536241/NikonSpinningDisk/260127_ARMC5mAC_PhosphoEU/20260203_171323_021/QUANTIFICATION \
  --input_dir /srv/scratch/berrylab/z3536241/NikonSpinningDisk/260127_ARMC5mAC_PhosphoEU/20260203_171323_021/OME-TIFF-MIP \
  --output_dir /srv/scratch/berrylab/z3536241/NikonSpinningDisk/260127_ARMC5mAC_PhosphoEU/20260203_171323_021/SEGMENTATION

conda deactivate
