#!/bin/bash

### quantify in parallel

#PBS -N batch_run_quantification
#PBS -l select=1:ncpus=1:mem=16gb
#PBS -l walltime=00:20:00
#PBS -o /home/z3536241/src/blana/Alex/PBS/log/
#PBS -e /home/z3536241/src/blana/Alex/PBS/log/

### The following parameter is modulated at runtime to specify the
### batch number on each node. Batches should run from zero to N_BATCHES-1
### to process all files

#PBS -J 0-1999

###---------------------------------------------------------------------------

source /home/z3536241/.bashrc
conda activate berrylab-py310

cd $PBS_O_WORKDIR

python /home/z3536241/src/blana/Alex/251020_mACmChPOLR2A_Incucyte/run_quantification.py \
  --id ${PBS_ARRAY_INDEX} \
  --features_dir /srv/scratch/berrylab/z3536241/Incucyte/251020_mACmChPOLR2A_Incucyte/QUANTIFICATION \
  --input_dir /srv/scratch/berrylab/z3536241/Incucyte/251020_mACmChPOLR2A_Incucyte/ROWE \
  --output_dir /srv/scratch/berrylab/z3536241/Incucyte/251020_mACmChPOLR2A_Incucyte/SEGMENTATION

conda deactivate
