```{r setup_r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls())
library(tidyverse)
library(patchwork)

cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
```

```{r}
read_quantification <- function(dir_name) {
  csv_files <- Sys.glob(file.path(dir_name,"*.csv"))
  dt_list <- lapply(csv_files, data.table::fread)
  df <- tibble(path = csv_files,
               feature_values = dt_list) %>%
    mutate(dir_name = dir_name,
           file_name = basename(path),
           feature_values = purrr::map(feature_values,tibble)) %>%
    separate(file_name,into = c("well_name","ch1","ch2","ch3","ch4","sample","id"),sep="[,_.]", extra = "drop") %>%
    mutate(well_name = str_replace(well_name, "^Well", ""),
           field_id = as.integer(id))
  return(df)
}
```

```{r}
data_dir_images <- "/srv/scratch/berrylab/z3536241/NikonSpinningDisk/260515_mACPOLR2A_CRC_EU/20260519_171947_338/"
data_dir_quant <- "/srv/scratch/berrylab/z3532965/NikonSpinningDisk/260515_mACPOLR2A_CRC_EU/20260519_171947_338/"
plate_layout_file <- "/srv/scratch/z3532965/src/blana/Alex/260515_mACPOLR2A_CRC_EU/260515_mACPOLR2A_CRC_EU.csv"

# Read plate layout
plate_layout <- read_csv(plate_layout_file, show_col_types = FALSE) %>%
  rename(well_name=WELL)

# Read and process quantification data
f <- read_quantification(file.path(data_dir_quant, "QUANTIFICATION_NUCLEOPLASM")) %>%
     dplyr::mutate(data_dir = dirname(dirname(path))) %>%
     dplyr::select(-c(ch1, ch2, ch3, ch4, sample))

# Process metadata
m <- tibble(data_dir = data_dir_images) %>%
  dplyr::mutate(image_dir = purrr::map_chr(data_dir_images, ~file.path(.,"OME-TIFF-MIP"))) %>%
  dplyr::mutate(metadata_file = purrr::map(image_dir, ~list.files(., pattern = "metadata.csv$"))) %>%
  unnest(metadata_file) %>%
  mutate(dat = purrr::map(file.path(image_dir, metadata_file), ~read_csv(., show_col_types = FALSE))) %>%
  separate(metadata_file, into = c("well_name", "ch1", "ch2", "ch3", "ch4", "sample"), sep = "[,_.]", extra = "drop") %>%
  unnest(dat) %>%
  mutate(well_name = str_replace(well_name, "^Well", ""),
         field_id = as.integer(field_id)) %>%
  dplyr::select(-c(ch1, ch2, ch3, ch4, sample)) %>%
  left_join(plate_layout, by = "well_name")

# Join metadata with quantification data
dat <- right_join(m, f, by = join_by(well_name, field_id), suffix = c("_images","_quant")) %>%
  unnest(feature_values) %>%
  mutate(unique_id = paste(well_name, label, sep = "_"))

```

```{r}

source("/srv/scratch/z3532965/src/blana/Scott/plot_plate_layout.R")

plate_layout %>% group_by(CELL,DRUG_CONCENTRATION,TIME_MINUTES,EU,PRIMARY,CLICK) %>%
  count()

plot_plate_layout(plate_layout, color_by = "EU", title = "EU")
plot_plate_layout(plate_layout, color_by = "CLICK", title = "Click reaction")
plot_plate_layout(plate_layout, color_by = "CELL", title = "Cell type")
plot_plate_layout(plate_layout, color_by = "DRUG", title = "Drug")
plot_plate_layout(plate_layout, color_by = "DRUG_CONCENTRATION", title = "Drug (µM)")
plot_plate_layout(plate_layout, color_by = "TIME_MINUTES", title = "Time (min)")
plot_plate_layout(plate_layout, color_by = "PRIMARY", title = "Primary antibody")

```
```{r}
names(dat)

# EU is Nucleus_intensity_mean_647 or Nucleoplasm_intensity_mean_647_mean
# Check Nucleoplasm_area_sum / Nucleus_area across conditions

```

```{r}
dat_subset <- dat %>% 
  filter(PRIMARY=="Total Pol II (F12)") %>%
  filter(EU=="EU 1 mM, 30 mins") %>%
  filter(CLICK=="AF647 azide click") %>%
  filter(CELL=="HCT116 OsTIRF74G mAC-POLR2A Clone 5")

bkgrd_dat <- dat %>% 
  filter(EU=="No addition") %>%
  filter(CLICK=="AF647 azide click") %>%
  group_by(well_name) %>%
  summarise(mean_EU_bkgrd = mean(ErodedNucleus_intensity_mean_647_mean,na.rm=T),
            mean_secondary_background = mean(ErodedNucleus_intensity_mean_561_mean,na.rm=T))

bkgrd_summary <- bkgrd_dat %>% ungroup() %>%
  summarise(mean_EU_bkgrd = mean(mean_EU_bkgrd),
            mean_secondary_background = mean(mean_secondary_background))
  
bkgrd_summary
```
```{r}

dat_subset %>%
  mutate(ratio_nucleoplasm = Nucleoplasm_intensity_mean_561_mean / ErodedNucleus_intensity_mean_561_mean) %>%
  group_by(DRUG_CONCENTRATION) %>%
  summarise(mean_ratio = mean(ratio_nucleoplasm,na.rm=T))

dat_subset %>%
  mutate(ratio_nucleoplasm = Nucleoplasm_intensity_mean_647_mean / ErodedNucleus_intensity_mean_647_mean) %>%
  group_by(DRUG_CONCENTRATION) %>%
  summarise(mean_ratio = mean(ratio_nucleoplasm,na.rm=T))

```


```{r}



dat_subset %>% 
  ggplot(aes(y=Nucleoplasm_area_sum/ErodedNucleus_area_sum,x=interaction(DRUG,DRUG_CONCENTRATION))) +
  geom_boxplot()



dat_subset %>% 
  group_by(well_name,DRUG,DRUG_CONCENTRATION) %>%
  filter(!is.na(Nucleoplasm_intensity_mean_647_mean)) %>%
  summarise(mean_nucleoplasm_EU = mean(Nucleoplasm_intensity_mean_647_mean - bkgrd_summary$mean_EU_bkgrd),
            mean_nucleus_EU = mean(ErodedNucleus_intensity_mean_647_mean - bkgrd_summary$mean_EU_bkgrd)) %>%
  group_by(DRUG,DRUG_CONCENTRATION) %>%
  summarise(across(c(mean_nucleoplasm_EU,mean_nucleus_EU),c(sd=~sd(.),mean=~mean(.)))) %>%
  mutate(LOG_DRUG_CONCENTRATION=if_else(DRUG_CONCENTRATION==0,-1,log10(DRUG_CONCENTRATION))) %>%
  ggplot(aes(x=mean_nucleus_EU_mean,y=mean_nucleoplasm_EU_mean,colour=LOG_DRUG_CONCENTRATION)) + 
    geom_abline() +
  geom_point() + 
  geom_errorbar(aes(ymin=mean_nucleoplasm_EU_mean-mean_nucleoplasm_EU_sd,ymax=mean_nucleoplasm_EU_mean+mean_nucleoplasm_EU_sd),width=4) +
  geom_errorbarh(aes(xmin=mean_nucleus_EU_mean-mean_nucleus_EU_sd,xmax=mean_nucleus_EU_mean+mean_nucleus_EU_sd),width=4) +
  coord_cartesian(xlim=c(0,NA),ylim=c(0,NA)) +

  scale_x_continuous(name="5-EU incorporation\n(Nucleus, A.U.)",breaks=c(0,50,100)) +
  scale_y_continuous(name="5-EU incorporation\n(Nucleoplasm, A.U.)",breaks=c(0,50,100)) +
  scale_color_viridis_c(
    name="5-Ph-IAA\nconcentration",
    begin=0,
    end=0.8,
    breaks=c(-1,0,1,2,3),
    labels=c("Vehicle","1 nM","10 nM","100 nM","1 µM")) +
  theme_bw(base_size = 8) + 
  theme(panel.grid=element_blank(),
        aspect.ratio=1,
        legend.key.width = unit(3,"mm"),
        legend.key.height = unit(2,"mm"))

ggsave("Nucleoplasm_vs_Nucleus_EU.pdf",width=6,height = 4,units="cm")

```
```{r}
dat_plot <- dat_subset %>% 
  group_by(well_name,DRUG,DRUG_CONCENTRATION) %>%
  filter(!is.na(Nucleoplasm_intensity_mean_647_mean)) %>%
  summarise(mean_nucleoplasm_EU = mean(Nucleoplasm_intensity_mean_647_mean - bkgrd_summary$mean_EU_bkgrd),
            mean_nucleus_POLR2A = mean(ErodedNucleus_intensity_mean_561_mean - bkgrd_summary$mean_secondary_background),.groups='drop') %>%
  group_by(DRUG,DRUG_CONCENTRATION) %>%
  summarise(across(c(mean_nucleus_POLR2A,mean_nucleoplasm_EU),c(sd=~sd(.),mean=~mean(.))),.groups='drop') %>%
  mutate(LOG_DRUG_CONCENTRATION=if_else(DRUG_CONCENTRATION==0,-1,log10(DRUG_CONCENTRATION)))

normalisers <- dat_plot %>%
  filter(DRUG_CONCENTRATION==0) %>%
  select(mean_nucleoplasm_EU_normaliser=mean_nucleoplasm_EU_mean,
         mean_nucleus_POLR2A_normaliser=mean_nucleus_POLR2A_mean)

bind_cols(dat_plot,normalisers) %>%
  mutate(mean_nucleus_POLR2A_mean=mean_nucleus_POLR2A_mean/mean_nucleus_POLR2A_normaliser,
         mean_nucleus_POLR2A_sd=mean_nucleus_POLR2A_sd/mean_nucleus_POLR2A_normaliser,
         mean_nucleoplasm_EU_mean=mean_nucleoplasm_EU_mean/mean_nucleoplasm_EU_normaliser,
         mean_nucleoplasm_EU_sd=mean_nucleoplasm_EU_sd/mean_nucleoplasm_EU_normaliser) %>%
ggplot(aes(x=mean_nucleus_POLR2A_mean,y=mean_nucleoplasm_EU_mean,colour=LOG_DRUG_CONCENTRATION)) + 
  geom_abline() +
  geom_point() + 
  scale_color_viridis_c(
    name="5-Ph-IAA\nconcentration",
    begin=0,
    end=0.8,
    breaks=c(-1,0,1,2,3),
    labels=c("Vehicle","1 nM","10 nM","100 nM","1 µM")) +
  geom_errorbar(aes(ymin=mean_nucleoplasm_EU_mean-mean_nucleoplasm_EU_sd,ymax=mean_nucleoplasm_EU_mean+mean_nucleoplasm_EU_sd),width=0.04) +
  geom_errorbarh(aes(xmin=mean_nucleus_POLR2A_mean-mean_nucleus_POLR2A_sd,xmax=mean_nucleus_POLR2A_mean+mean_nucleus_POLR2A_sd),width=0.04) +
  scale_x_continuous(name="POLR2A immunofluorescence (F12)", limits=c(0,1.15),breaks=c(0,0.5,1)) +
  scale_y_continuous(name="5-EU incorporation\n(Nucleoplasm)", limits=c(0,1.15),breaks=c(0,0.5,1)) +
  theme_bw(base_size = 8) + 
  theme(panel.grid=element_blank(),
        aspect.ratio=1,
        legend.key.width = unit(3,"mm"),
        legend.key.height = unit(2,"mm"))
ggsave("Nucleoplasm_EU_vs_Nucleus_POLR2A.pdf",width=6,height = 4,units="cm")
```


